### ISSUE TITLE
Rebrand - Homepage

### ISSUE THREAD

**Issue by Nevtep** [OmniLayer/omniwallet#1110]
**Implement New Architecture and restructure controllers**
- Move the HomeCtrl from controller.js into /js/controllers/landing/home.js
- Define the HomeController inside the omniControllers module
- Define a message in the websocket server that returns balances for an address when called.
- Use websocket for balances

**Implement New Design and restructure views**
- Replace "row" tags for proper divs with bootstrap clases.
- Follow latest UI definitions

**Comment by achamely** [comment]
completed with new design on staging
