### ISSUE TITLE
Enable Omniwallet to work on testnet

### ISSUE THREAD

**Issue by ripper234** [OmniLayer/omniwallet#118]
As a separate deployment of Omniwallet.

This should be a configuration on the deployment that will cause the entire Omniwallet operation to run on testnet. This is not like running on Test Mastercoins (that are still based on real bitcoins underneath), but rather on testnet bitcoins.

This is essential to be able to test Omni without paying real fees.

**Comment by gggin** [comment]
http://testnet.omniwallet.org/ is down. Is there any other website?

**Comment by achamely** [comment]
@gggin no, we currently are not offering a testnet version of the wallet at this time

**Comment by gggin** [comment]
OK then I'm trying to setup a omni-core.
