### ISSUE TITLE
What happens to the password when a password reset is canceled?

### ISSUE THREAD

**Issue by pelekoudas** [OmniLayer/omniwallet#1212]
While in a wallet user enters the password reset dialog. Enters the current password as validation. Then cancels out of the password change. Exits the wallet. Next initiates the login to the same wallet, but unchanged password is not recognized. Result: user is locked out of wallet.

Has this been seen before? I saw nothing in the issues list.

**Comment by achamely** [comment]
We've never seen/heard of this before and this should not be the case. The save session/wallet is only called on the success of the dialog. 

I just logged in and tried to recreate this and was not able. 
Logged in
Went to account settings
Entered password change dialog
Authenticated with old password
Got new password dialog
Canceled new password dialog
Logged out
Logged back in with original password (successfully)

**Comment by achamely** [comment]
@pelekoudas  Are you still not able to login with your original password?

**Comment by achamely** [comment]
resolved with #1290
