### ISSUE TITLE
Staging: a send isn"confirm" in the UI

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omniwallet#1218]
Even though the transaction was actually broadcasted, the view doesn't confirm the send. This may create the impression the send failed, resulting in more than one send.

![no_send_1](https://cloud.githubusercontent.com/assets/5836089/7894777/68802c3c-0671-11e5-8908-2b0a922e663c.png)

After some time a timeout error is shown.

![no_send_2](https://cloud.githubusercontent.com/assets/5836089/7894779/6d092ae2-0671-11e5-89cc-1b4b994edb40.png)

**Comment by achamely** [comment]
duplicate of #1219
