### ISSUE TITLE
Can't send bitcoins

### ISSUE THREAD

**Issue by gabesbit** [OmniLayer/omniwallet#1227]
Can't send bitcoins from https://www.omniwallet.org
Red error message show up: "Funds could not be sent: Error preparing transaction: global name 'fee_total_satoshi' is not defined"

**Comment by gabesbit** [comment]
It works now!

**Comment by achamely** [comment]
Yup, we pushed some patches last friday which added an uninitialized variable that affected the bitcoin sends.  this was fixed in #1228
