### ISSUE TITLE
Funds could not be sent: Error preparing transaction: undefined

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omniwallet#1242]
A user on [bitcointalk.org reported](https://bitcointalk.org/index.php?topic=558012.msg13063136#msg13063136):

> Does anyone from the dev team read tickets at zendesk? I created one and been waiting for 4 days for it to be resolved. I can't send funds from the online wallet ("Funds could not be sent: Error preparing transaction: undefined").
Edit: tried to do to it using different browsers with no plug-ings enabled, no luck.

**Comment by dexX7** [comment]
Appearingly this is a duplicate of #1232, but still unresolved.

**Comment by Nevtep** [comment]
I've seen this happen when the tx needs multiple inputs for the amount the user is trying to send, the logs should say more

**Comment by achamely** [comment]
There was a bug with multiple inputs not being handled correctly (especially when it was more than 9 inputs)  but we rolled out some patches to fix that week before last. 
If we can try to coordinate with the user to try again when we can watch the logs it would be beneficial to try and track down the issues

**Comment by achamely** [comment]
Spent some time tracking down the users reported issue this morning. Bug found and fix deployed.

**Comment by chadrickm** [comment]
Not resolved - Just got this same issue today.
