### ISSUE TITLE
Funds could not be sent: Error preparing transaction: undefined

### ISSUE THREAD

**Issue by chadrickm** [OmniLayer/omniwallet#1248]
I know this is a duplicate ticket ( #1232 , #1242 ) but the others are closed so I'm adding a new one. This happened to me this morning...

**Comment by chadrickm** [comment]
And tried it again with this error message:
Funds could not be sent: Transaction rejected by the network. Contact a developer.

One of the folks on Maidsafe forum says it might be a issue with the network being too busy? https://forum.safenetwork.io/t/omniwallet-transaction-issue/6383/6

**Comment by achamely** [comment]
Hmm, chad, can you provide the address you where sending from /to so i can check the logs. 
If you'd rather email the info use the address on the contact us page of www.omniwallet.org

**Comment by chadrickm** [comment]
I was sending from 13vud4dqnm57jYsTYHJ9F4L7taHWGiLETB and I was able to get it to go through by just doing it 3 times in a row. Still, not fun to have to hope that it will work ;)

**Comment by achamely** [comment]
Thanks Chad, we identified the issue (bitcoin signing library was using older methods to sign tx's that are no longer allowed on newer network nodes).  
We put in a patch that should help until next update to replace the library.  Let us know if it helps

**Comment by achamely** [comment]
fixed with #1249
