### ISSUE TITLE
On staging, My Addresses page shouldn't have a balance summary for each address

### ISSUE THREAD

**Issue by marvgmail** [OmniLayer/omniwallet#1255]
It doesn't make any sense to show a cumulative total amount of all the properties owned by an address, i.e. there's no meaning to the total number of bitcoins plus USDT plus ... belonging to an address. It would be like adding the number of apples plus oranges plus bananas plus ... All it would mean is the total number of "things" owned by the address.

It does make sense to show the cumulative value owned by each address, though.

Currently, the page shows the number of bitcoins belonging to the address, but it doesn't show that it is the number of bitcoins.

**Comment by achamely** [comment]
fixed
