### ISSUE TITLE
GET URL for Omniwallet balance check

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omniwallet#1288]
It would be nice to be able to create a hyperlink to a balance check **HTML page** for display in a  browser for a particular address.

For example: https://www.omniwallet.org/balancecheck/1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P

OmniExplorer supports this with URLs like the following: 

http://omniexplorer.info/lookupadd.aspx?address=1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P

**Comment by zathras-crypto** [comment]
Hey Sean,

Just a quickie mate - if it helps - no need to load a page, you can just call the API.  Here are some popular calls, but there are many more - just shout if you're looking for something specific.

Hope your work on OmniPortfolio is going well :)

Thanks
Z

Retrieve balance:
http://omnichest.info/ask.aspx?api=balance&address=1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P&prop=1

Retrieve reserved balance:
http://omnichest.info/ask.aspx?api=reservedbalance&address=1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P&prop=1

Check if a transaction is valid:
http://omnichest.info/ask.aspx?api=checkvalid&txid=a3c7b8df8c1295626a77b034b74097b7d640520a11170088fa5e4c4584b35c9f

Fetch a transaction:
http://omnichest.info/ask.aspx?api=fetchtx&txid=a3c7b8df8c1295626a77b034b74097b7d640520a11170088fa5e4c4584b35c9f

Lookup the name of a property:
http://omnichest.info/ask.aspx?api=propertyname&prop=3

Retrieve the total number of tokens for a property:
http://omnichest.info/ask.aspx?api=totaltokens&prop=3

**Comment by msgilligan** [comment]
In this case I'm actually looking for a page to open in a browser window.

**Comment by zathras-crypto** [comment]
Ahh I see, in that case please disregard :)

**Comment by projectoblio** [comment]
What is the difference between reserve balance, frozen balance, and normal balance? Thanks

**Comment by achamely** [comment]
@projectoblio 
Normal balance is a balance that is immediately usable and has nothing affecting it. 
Reserved balances are balances that are currently locked/tied up in an omni protocol process (like offered for sale on the exchange or similar)
Frozen are funds that have been explicitly locked/frozen by the token issuer and can not be moved or used unless unfrozen by the token issuer.

**Comment by msgilligan** [comment]
@achamely Is there an Omniwallet URL that will show balances, equivalent to the following OmniExplorer URL: https://omniexplorer.info/address/1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P
