### ISSUE TITLE
An example how to use this call

### ISSUE THREAD

**Issue by dallyshalla** [OmniLayer/omniwallet#1291]
Get a page of transaction & offer information

HTTP GET /v1/transaction/general/{Currency}_{4 digit page}.json Returns:

Can provide an example of a url call to get a page of the transactions?

**Comment by achamely** [comment]
at the moment the call is being refactored and the documentation doesn't match well. 

You can use the current call (https://www.omniwallet.org/v1/transaction/general/)  which returns the last 10 transactions
