### ISSUE TITLE
Transfer synero find error

### ISSUE THREAD

**Issue by ForestCoin** [OmniLayer/omniwallet#1319]
the error code was:-211 
the error message was:   
Error creating transaction(wallet may be locked or fees may not be sufficient)

but my  wallet can be transferred maidsafe。have enough bitecoin and not locked。 why?  
What conditions need to transfer synereo

**Comment by achamely** [comment]
@ForestCoin Are you getting this error with Omniwallet.org or in the Omnicore Client?

It sounds like it's in the Omnicore client in which case your BTC needs to be on the sending address (same address your synero is on). 
Also there is a dedicated github for the Omnicore client (see https://github.com/OmniLayer/omnicore for that project)

**Comment by ForestCoin** [comment]
@achamely 
I can't understand your means. now, I want to take  synereo to poloniex from my omnicore wallet,but always prompt error. such as

the error code was:-211 
the error message was:
Error creating transaction(wallet may be locked or fees may not be sufficient)

or

Warning:the sending address is low on btc for transaction fees.please topup the btc balance  for the sending address to send omni layer transactions

**Comment by ForestCoin** [comment]
How do I operate on my omnicore wallet?  thank you

**Comment by dexX7** [comment]
@ForestCoin: send a smaller amount of bitcoin to the address currently holding the synereo. These bitcoin are required for the transaction fee and additional data outputs.

**Comment by ForestCoin** [comment]
@dexX7  my omnicore wallet  have 0.0255 btc。isn't that enough?how much  I need to turn to the number of btc  into the omnicore wallet?

**Comment by ForestCoin** [comment]
I am currently testing the omnicore wallet. the wallet include  0.0255btc、0.1omni、16maidsafecoin、3synereo。  maidsafe can be transfer.but  omni and synereo transfer wrong.

**Comment by dexX7** [comment]
@ForestCoin: 0.0255 BTC is enough, but did you make sure it's in the address holding the synero, or do you use another address for maidsafe? If so, you need to send some of the BTC to the address holding the synero.

**Comment by ForestCoin** [comment]
@dexX7  my omnicore wallet  have two  synereo  address. one address can  be  transfer synereo to  poloniex。but another address is wrong. so, two  address must have btc? This experience is difficult for our foreign users to operate

**Comment by zathras-crypto** [comment]
Hi,

Any address used to send Omni requires a small amount of BTC for fees.

Thanks

**Comment by ForestCoin** [comment]
if there are more than ten addresses in my omnicore wallet, then I mustt to give these addresses to bitcoin? Why don't you have a total address to pay for the fee.

**Comment by zathras-crypto** [comment]
> if there are more than ten addresses in my omnicore wallet, then I mustt to give these addresses to bitcoin? 

Yes.   An Omni transaction is a Bitcoin transaction with extra metadata.  Bitcoin is required to use the Bitcoin network.

> Why don't you have a total address to pay for the fee.

Cryptographically signing an input from the sender is a fundamental concept of cryptocurrency.  If we use a different address for the fee and don't include any bitcoin input from the sending address, there is no way to prove the sending address authorized the transaction.

We already support paying *some* of the fees from a central address, but there is no getting away from the fact that the sending address needs to supply a small amount of Bitcoin as an input, and then cryptographically sign it, as this is how we verify transactions.

**Comment by ForestCoin** [comment]
thank you

**Comment by zathras-crypto** [comment]
No problem :)

**Comment by initsysctrl** [comment]
you need use cli "walletpassphrase password timeout" to unlock wallet

**Comment by ilaer** [comment]
> you need use cli "walletpassphrase password timeout" to unlock wallet

what do your mean?how to unlock?
