### ISSUE TITLE
History doesn't show BTC transactions

### ISSUE THREAD

**Issue by owen-kellie-smith** [OmniLayer/omniwallet#1323]
http://blockchain.info/address/1M2BgbWixvpvRyCGF3WBQ6hTpxjX9gNfdh shows transactions into and out of the address held at omniwallet.  

but

https://www.omniwallet.org/  Omniwallet > History doesn't show any transactions
![omniscreen](https://cloud.githubusercontent.com/assets/7147546/18817301/36e37276-8355-11e6-9b62-2dc629abbeb7.png)

**Comment by owen-kellie-smith** [comment]
Is it because it is a BTC-only transation?  https://github.com/OmniLayer/omniwallet/wiki/Omniwallet-History-and-missing-BTC-transactions

**Comment by achamely** [comment]
Yes, at the moment the history page only show Omni protocol transactions.  For bitcoin only transactions we recommend a block explorer like blocktrail.com or blockchain.info
