### ISSUE TITLE
{{'COMMON.LOADING' | translate}} error on splash page in Safari

### ISSUE THREAD

**Issue by mabuse68** [OmniLayer/omniwallet#1344]
OSX user: No page shows up on Safari 9.1.3, an error is reported as mentioned in the subject (see screenshot attached)
![omniwallet](https://cloud.githubusercontent.com/assets/970726/19211335/4fd69cc4-8d3a-11e6-9f5f-79437aa27419.jpg)

Deleted cookies and cache, stays the same.

Firefox seems to be unaffected.

**Comment by achamely** [comment]
Confirmed issue is in safari 9. Interim solution is either upgrade to 10 or use chrome/firefox

**Comment by achamely** [comment]
Should be resolved now with https://github.com/OmniLayer/omniwallet/pull/1359
