### ISSUE TITLE
Can not send coins.  

### ISSUE THREAD

**Issue by URAshoaf** [OmniLayer/omniwallet#1491]
Trying to send SafeX coins, have over 900K Satoshi and cant spend the 64,000 Satoshi for the miner fee.

 System error reports:

: Not enough funds, try again. Needed: 0.0006376499999999999995057772817 but Have: 0.0000273

**Comment by URAshoaf** [comment]
It ended up working- bummer it took so long to update the fact that I had enough BTC for the transaction.  Thanks all the same.

**Comment by ForestCoin** [comment]
I have this problem, too

**Comment by achamely** [comment]
@URAshoaf we were having some latency issues with balance updates but a fix was pushed earlier this week. If you encounter the issue again let us know
