### ISSUE TITLE
Server error, try again later 

### ISSUE THREAD

**Issue by joshhart12345** [OmniLayer/omniwallet#1512]
Hi

I've had the Server error, try again later message for over a day now when trying to log in - is there some dvelopment going on at the moment or another reason as to why I can't log in? 

Thanks
Josh

**Comment by Frankenmint** [comment]
Hey josh was it ever working for you or is this your first time installing?  I did some digging and see that I"m getting this error from the connection being refused:

`... connect() failed (111: Connection refused) while connecting to upstream ... `

I suspect that nginx is not able to successfully connect to the socket.io service on the backend and am trying to pin this down now - will reply with more details if I figure it out for my specific issue.

**Comment by achamely** [comment]
hey Josh, there was an unfortunate issue that caused the system to lock up at that point. We were able to clean things up a bit after your message.
