### ISSUE TITLE
Can't send BTC

### ISSUE THREAD

**Issue by sgjenks01** [OmniLayer/omniwallet#1513]
I have an OmniWallet with 2 addresses. I am simply trying to send the BTC at one address to the address that has USDT in it. 

When I put in the addresses and amount to send, a green button appears which offers to "Re-estimate Transaction Cost".  But when I push that button, it disappears and a grayed out "Next" button appears and there is no further progress from then on (hung). 

Any hints on how to make this go?

**Comment by MIKEJC8** [comment]
who can help 2.5btc to me

**Comment by sgjenks01** [comment]
I got an answer to my question. The wallet has to have BTC in it to "fuel" the wallet because all the coins/tokens are based on and trade on the BTC blockchain, so it takes BTC to pay the miners.

**Comment by MIKEJC8** [comment]
who can help 2.5btc to me send to this btc address line :1P5tA9JMBmZR9bFHMY3cJTiQy1dSM2EW44 :+1:
