### ISSUE TITLE
Sending Omni fails with message: Not enough funds, try again.

### ISSUE THREAD

**Issue by XBase-xOR** [OmniLayer/omniwallet#1552]
The exact message I get is:
"Not enough funds, try again. Needed: 0.0001575600000000000002399686352 but Have: 0"

I am trying to send 1 Omni from the address 1LB2AZvQrLaBxti8gkUHRfZ94oKF1dQmQS. The wallet overview says this address currently has 0.0005 BTC and 100 Omni. Should be sufficient Omni to transfer and also sufficient BTC for the transaction fees (which the dialog says is 0.0002067 Bitcoins).

So what does "Have: 0" mean? What can I do to fix this?

**Comment by achamely** [comment]
It means you have 0 bitcoin in your sending address. All transactions on the Omni Protocol need bitcoin in order to be created and sent. 
If you fund that address with the required/specified amount of BTC you will be able to continue

**Comment by XBase-xOR** [comment]
As I have written the address was funded with 0.0005 BTC while the error message says I needed 0.0002067 - so the same interface that reported "Have: 0" also reported I have 0.0005 BTC. You don't see this as an error and just close the case? Meh.

**Comment by achamely** [comment]
@XBase-xOR sorry let me clarify
I do see that it is possible at the moment for there to be a difference in displayed balance and usable balance. 
When sending a tx the underlying btc needs to be confirmed for the tx to be creatable. 
The error message you listed indicates you had an unconfirmed/pending balance that was not yet usable.

**Comment by XBase-xOR** [comment]
@achamely That makes a lot more sense. Thanks for the clarification.
