### ISSUE TITLE
Stored MAID in electrum with 2fa, need help 

### ISSUE THREAD

**Issue by Usogeking** [OmniLayer/omniwallet#1558]
I was stupid enough to store MAID in my electrum wallet using 2fa, so the address I have my MAID on 3Jnz4bDfgmB9DYiZkxZ....... does contain the MAID according to www.omniwallet.org, but the corresponding private key does not and shows this address : 1Jgt1MzurJrTHByGmBdhLc.....

I know this address (3Jnz4bDfgmB9DYiZkxZ.......) does not have a single private key (but multiple or something) which makes me wonder how I will ever retrieve the MAID on it, or is it just locked up in my wallet forever?

**Comment by achamely** [comment]
@Usogeking  Sorry for the delayed response. There is a process for this though it can be a little tricky. 

 - Step 1) (If you have a 2FA wallet) Create a new electrum 2FA wallet and choose the option to recover it from your recovery seed (It should ask you to disable 2fa and have the master keys 
in the restored wallet. This is what you want. Once created make sure the address you are recovering from is displayed.
 - Step 2) Make sure you have about 0.005 BTC on the address you need to recover/send the tokens from
 - Step 3) Goto 'Wallet->Addresses' to enable the address menu, then freeze EVERY Address that has a BTC balance EXCEPT the Address you are recovering from (right click the address and choose freeze)
 - Step 4) Go to electrum settings window and open the preferences. 
 -- Go to the 'Fees' tab and CHECK both 'Use Dynamic Fee's and 'Edit fees manually'
 -- Go to the "Transactions" tab and make sure to UNCHECK both 'use change address' and 'use multiple change addresses'
 -- Next go to the 'Appearance' tab and change Base Units to 'BTC' . You can revert all these settings later if you want. 
 - Step 5) What is the address you want to send/recover your tokens to (this should be an omni enabled address/wallet/service that accepts your tokens).  Replaced the "Your-Recovery-Destination-Maidsafe-enabled-address" with that recovery address in step 6
 - Step 6) Go to the 'Tools-> Pay To Many' option. 
-Paste in the following two lines:

OP_RETURN 6f6d6e69000000000000000300000000000000fa, 0
Your-Recovery-Destination-Maidsafe-enabled-address, 0.00000546

Note: If successful this will send 250 Maidsafe to the address you use to replace "Your-Recovery-Destination-Maidsafe-enabled-address"

 - Step 7) Adjust the fee's tab for ~ 5 blocks for confirmations

If you want a second review before you submit the transaction then 
-Send a screenshot of this page as it exists. 
-Then click the 'Preview' tab and send a screenshot of the preview tab as well
-Lastly on the Preview page use the 'save transaction' option and send the saved transaction for final review.
For security you can send this stuff to the support email address listed on https://www.omniwallet.org/about/contact

If you do not want a review you can just go ahead and review / sign / broadcast the tx as it is

**Comment by Usogeking** [comment]
Hey Adam, 

Thank you for your reply. I followed all your steps to the best of my ability and adapted for my other address that holds 3590 MAID: ```36kGXoWWmTrNsg92jk1GXNcPwkW5zDfiwG``` 

However, when I try to preview the transaction, Electrum warns me that the first line is invalid.
![image](https://user-images.githubusercontent.com/31544146/34876757-4cc46172-f7a3-11e7-8214-ba42db06960b.png)

Do you have any idea what causes this and how I can circumvent it?
Any help would be greatly appreciated.

**Comment by achamely** [comment]
@Usogeking what version of electrum are you using?

**Comment by Usogeking** [comment]
Hey @achamely,

I tried it again on my desktop and it worked!!! I succesfully made two transactions from my wallet. 
Thank you so much for your time and help 😄

**Comment by achamely** [comment]
awesome glad you were able to recover the funds :+1:
