### ISSUE TITLE
Create Crowdsale Fails

### ISSUE THREAD

**Issue by blackkaaaht** [OmniLayer/omniwallet#1560]
"Create Crowdsale" works in test mode; fails in actual mode.

https://www.omniwallet.org/assets/crowdsale 

Do you have a workaround, or can you suggest another exchange that is compatible with Omni tokens?

**Comment by achamely** [comment]
If you tried to create tokens back to back its most likely your btc balance was still unconfirmed from the previous transaction. Once the balance confirms you would be able to continue
