### ISSUE TITLE
Custom fee cannot be set below 0.0001 BTC

### ISSUE THREAD

**Issue by shubidoo** [OmniLayer/omniwallet#1561]
Hey guys,

I just noted that when trying to send a transaction in Omniwallet, I cannot choose a custom fee below 0.0001 BTC. Is this intentional? 

From the current mempool size, I would have been able to get away with less transaction fees, but I was forced to choose this amount as it wouldn't let me set a truly custom fee. I tried finding an explanation for this but was unable to do so. 

I think it would be great if I could choose my own amount, as little as 10 satoshis/byte perhaps, in order to save on transaction costs when the mempool permits.

**Comment by achamely** [comment]
@shubidoo yes this is intentional. At the moment the custom fee is not a fee/kb it is a flat fee.
The use of fee/kb is in the dynamic calculations done by the normal/fast/faster  speeds.  
We will be rolling out some updates to allow for better fee handling/specifications this year
