### ISSUE TITLE
Login Malfunction: Server Error, Try again later

### ISSUE THREAD

**Issue by oketai** [OmniLayer/omniwallet#1562]
Trying to log in since yesterday. Keep getting the same message "Server Error, Try again later." When will this be fixed? Thanks.

**Comment by oketai** [comment]
Anyone out there?

**Comment by sgjenks01** [comment]
@oketai I am having the same issue for about the same amount of time, maybe a bit longer.

**Comment by dacoinminster** [comment]
Might be offline while they update the code to deal with the Tether theft

**Comment by sgjenks01** [comment]
Interesting idea. How do you think Bitfinex getting hacked is related to OmniWallet being down?

**Comment by oketai** [comment]
The notification on the website/ login page changed. Now it says they're doing an update and that this is taking longer than expected. ETA: Nov. 27. @dacoinminster: You're right - could be that they're fixing sth related to the Tether issue. Thanks for your input. However I wish that Omniwallet people would bring some light into the dark though.
