### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by zekylaf** [OmniLayer/omniwallet#1564]
Hi, is there a simple way to install omniwallet locally?

Thanks

**Comment by dacoinminster** [comment]
I believe the devs use virtual machines for this, but I haven't done the whole process myself.

**Comment by achamely** [comment]
@zekylaf  Unfortunately Omniwallet in its current form isn't really designed to be installed/run locally/independently as it needs to be paired with all several dependencies (omniengine, omnicored, and a corresponding database. ) Omnicored being in and of itself a standalone wallet .

If all of those are not setup properly and connected properly omniwallet won't work.
The code is currently published for transparency and audit but at this time not for individual use.
We are working on an update this year which will abstract things out a bit more and allow Omniwallet to operate on a bit more stand alone with tie ins to some public apis
