### ISSUE TITLE
Error sending - "Funds could not be sent: Server error"

### ISSUE THREAD

**Issue by russellpwirtz** [OmniLayer/omniwallet#1574]
When trying to create an unsigned transaction in omniwallet to send BTC, I get to the end of the process, and when I click "Send" I get a red error:
"Funds could not be sent: Server error"
I've tried different amounts, different recipient addresses - all the same result.

**Comment by dacoinminster** [comment]
@dexX7 or @achamely - any idea what could be going on with this?

**Comment by achamely** [comment]
@russellpwirtz the most common cause of that error is generally if your source address has an unconfirmed btc balance. 
We are working to add some additional updates to properly show/differentiate confirmed balances from unconfirmed balances. 
If you want to contact the  support email team: https://www.omniwallet.org/about/contact   you can provide your source address and we can check the logs to see exactly what was happening
