### ISSUE TITLE
Why I got "Internal Server Error" when calling API

### ISSUE THREAD

**Issue by vincentwang0736** [OmniLayer/omniwallet#1575]
hi all,
I just finished manually installing local omniwallet following tourist.
But When I call the api as "http://xx.xx.xx.xx/v1/transaction/values.json",I got "Internal Server Error".
I have installed omniwalled for a whole day.while I got this eriir in the end.my god!
Anyone can help me?

**Comment by achamely** [comment]
@vincentwang0736   the error can be from any number of reasons. 

Unfortunately Omniwallet in its current form isn't really designed to be installed/run locally/independently as it needs to be paired with all several dependencies (omniengine, omnicored, and a corresponding database. ) Omnicored being in and of itself a standalone wallet .

If all of those are not setup properly and connected properly omniwallet won't work. 
The code is currently published for transparency and audit but at this time not for individual use. 
We are working on an update this year which will abstract things out a bit more and allow Omniwallet to operate on a bit more stand alone with tie ins to some public apis

**Comment by vincentwang0736** [comment]
thank for your reply and I also want to know if I want to run omniwallet locally,must I install omnicore and synchronize  all the 177g data?

**Comment by achamely** [comment]
Yes
