### ISSUE TITLE
something wrong when calling the apis of omniwallet

### ISSUE THREAD

**Issue by vincentwang0736** [OmniLayer/omniwallet#1578]
something wrong when calling the apis of omniwallet
After installing omniwallet in ubuntu16.04, I tried on calling a getting api on my browser:

> http://xx.xx.xx.xx/v1/system/stats.json

But I got "502 Bad Gateway"

/var/log/nginx/error.log putput:

> *198 upstream prematurely closed connection while reading response header from upstream, client: 118.198.116.180, server: localhost, request: "GET /v1/system/stats.json HTTP/1.1", upstream: "uwsgi://127.0.0.1:1088", host: "47.94.136.67

And I didn't found uwsgi's log file ,So I want to ask where is uwsgi's log file by the way.
And what's the matter about 502 Bad Gateway？
thanks a lot!

**Comment by achamely** [comment]
At this time omniwallet is not designed for local installation as you actually need to have omniwallet, omnicore, omniengine and the omnidatabase setup, synced and current for things to work. it is provided for reference/code audit only.
We are working on some updates to allow it to be a bit more modular in the coming months and will announce accordingly when that is ready
