### ISSUE TITLE
Sent Maidsafe to GreenAddress 

### ISSUE THREAD

**Issue by ubuntuser11** [OmniLayer/omniwallet#1586]
Hello,

I transferred some Maid from Polonex to a Greenaddress multisignature wallet. For the Greenaddress the receiving address for multisig 2/2 starts with a 3 and I can not find the private key using all methods including using 24 word mnemonic bip-32. But is when adding the public key (that starts with 3) to Omni wallet it does show me  the Maid balance and history.  I also did greenaddress "garecovery" and got all private key and converted from "K" to "5" and imported to Omni wallet but still nothing shows.

Thank you for any help.

**Comment by ubuntuser11** [comment]
@achamely  Very happy. Thanks a lot. Where will I be sending the information? Will it be direct to you?

**Comment by achamely** [comment]
@ubuntuser11 You can use the omniwallet support email from https://www.omniwallet.org/about/contact
and we can manage the process through there for security

**Comment by ubuntuser11** [comment]
@achamely  Thanks a lot. I will provide the information to your omniwallet.org contact address as you recommend.  This is great.  I will note it here in Github when I send the email. Thanks a lot.
