### ISSUE TITLE
{{'COMMON.LOADING' | translate}} error in firefox, chrome,..

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [OmniLayer/omniwallet#1596]
Hello,
I have installed omniwallet and I get an error when trying to run the page, I have updated firefox and installed chrome, but the message still appears in both browsers. I have also erased the browser cache, but without solution.

I have seen the thread # 1344 but it does not seem that there is a solution for me.

Any ideas? maybe I should install before omnicore?

thanks greetings.

**Comment by achamely** [comment]
At this time omniwallet is not designed for local installation. it is provided for reference/code audit only. 
We are working on some updates to allow it to be a bit more modular in the coming months and will announce accordingly when that is ready
