### ISSUE TITLE
Error in omni_createrawtx_opreturn RPC call: {u'message': u'Transaction deserialization failed', u'code': -22}

### ISSUE THREAD

**Issue by AxlMaid** [OmniLayer/omniwallet#1634]
Hello,

I am trying to send a few MaidSafeCoin from Omniwallet to Poloniex but I always get the following error message: "Error in omni_createrawtx_opreturn RPC call: {u'message': u'Transaction deserialization failed', u'code': -22}"

Can you please help?

Thank you,

<img width="592" alt="maid" src="https://user-images.githubusercontent.com/30219645/39404967-a0ed5bd0-4b9c-11e8-9715-fab6ac2d7e1b.png">

**Comment by achamely** [comment]
@AxlMaid This issue should be fixed in the most recent patches we pushed last week. Can you please try again and close this issue if everything works

**Comment by AxlMaid** [comment]
Hello Adam,

As I was telling you last week all works fine now.

Thank you,

Alexandre
