### ISSUE TITLE
privkey from bitcoincore import to omnicore success but the  Address is not same with  bitcoincore address

### ISSUE THREAD

**Issue by adaipan** [OmniLayer/omniwallet#1642]

**Comment by achamely** [comment]
Issues opened here are for Omniwallet not Omnicore. 
Is your difficulty for Omniwallet or Omnicore?
If your difficulty is with Omnicore, please close this issue and repost in the Omnicore repo: https://github.com/OmniLayer/omnicore/issues
If your difficulty is with Omniwallet then please elaborate a little more on what you are doing and provide a step by step list of what you did leading up to your issue so we can try to assist.

**Comment by achamely** [comment]
@adaipan 
Issues opened here are for Omniwallet not Omnicore.
Is your difficulty for Omniwallet or Omnicore?
If your difficulty is with Omnicore, please close this issue and repost in the Omnicore repo: https://github.com/OmniLayer/omnicore/issues
If your difficulty is with Omniwallet then please elaborate a little more on what you are doing and provide a step by step list of what you did leading up to your issue so we can try to assist.

**Comment by adaipan** [comment]
privkey from bitcoincore import to omniwallet success but the Address is not same with bitcoincore address   
my bitcoin core address is 356fzuNpDsddcdbUKznWM7JCjnPXvm2y7e after import private key, the omniwallet address change to 1KyW5PnfNSR27qCu21UvNXcY932xeDbdXD

**Comment by achamely** [comment]
As you have already opened a support ticket with the staff we will close this issue to remove duplication as there is no bug with the platform, this is an issue with use of segwit address which is different
