### ISSUE TITLE
Problem with transaction

### ISSUE THREAD

**Issue by munesu180290** [OmniLayer/omniwallet#1661]
I made a withdrawal of 96USDT from my binance account into coincola. Unfortunately did not notice that the minimum deposit was 100USDT now I cannot find the funds. Is there a way to get the funds.

the Txid is : 741c788c566ebd5acfd57a4e74512a633887f72a340a19557efdbb794cb24f9a

**Comment by munesu180290** [comment]
Hi

They said transactions are not accumulative so that isn’t an option. Is there any other way?

Regards 

Walter

**Comment by dexX7** [comment]
Well, in this case I recommend not to use their service anymore, because that doesn't make much sense, at least to me.

The Omni Layer is balanced based and the total balance is the same, whether they receive an amount in one, or in multiple, transactions.

**Comment by munesu180290** [comment]
So its their platform that is ripping me off in this case? Figured as much 

Thanks a lot for your assistance 

Regards 

Walter

**Comment by dexX7** [comment]
I don't know anything about their intentions, nor have I heard about their platform, but this certainly is odd and doesn't make much sense - at least to me, based on the given information.

**Comment by achamely** [comment]
While not uncommon we have seen some services have a minimum deposit amount. Unfortunately there is nothing we can do as they control their own platform and make the rules for their customers. The best we can recommend is asking them nicely to make an exception to their rules
