### ISSUE TITLE
omni_send转账不成功

### ISSUE THREAD

**Issue by wyh00544** [OmniLayer/omniwallet#1666]
有0.0002个BTC，转账报Error with selected inputs for the send transaction

**Comment by dexX7** [comment]
Hi @wyh00544,

please see:

https://github.com/OmniLayer/omnicore/wiki/Why-do-I-need-bitcoin-to-create-Omni-transactions%3F

Now in this particular case, it might be that your fee settings/estimation is too high, so 0.0002 BTC are not considered enough.
