### ISSUE TITLE
send 1200$ but recive 1$ in my btc wallet!!! help

### ISSUE THREAD

**Issue by CryptoVang** [OmniLayer/omniwallet#1669]
https://omniexplorer.info/tx/819b57683574a9c1104f1a9c4647174482580cc3dcd74ff8e1d32b7845ec1827
this my hash help me please

**Comment by CryptoVang** [comment]
send usdt omny from coinomi wallet , to btc adress in dsx ((( help to resolve problem

**Comment by dexX7** [comment]
Hi, please see:

https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F
