### ISSUE TITLE
Can's transfer, show error "Transaction rejected by the network. Reason: 64: scriptsig-not-pushonly"

### ISSUE THREAD

**Issue by CockyCat** [OmniLayer/omniwallet#1670]
I have a issue in use www.omniwallet.org:
 
I just import private from bitcoincore to www.omniwallet.org and imported is sucess, I can see my balance. 
    
Then Im transfer USDT,but show error ": Transaction rejected by the network. Reason: 64: scriptsig-not-pushonly".

What's wrong for this ?

Please help me, Thank you very much.

**Comment by achamely** [comment]
@CockyCat sorry for the delayed response, that error generally means the tx you are trying to broadcast was signed incorrectly. Can you please reach out to our support department email and provide the address you were trying to send from so they can check and see what might be happening.
