### ISSUE TITLE
Wallet error: 'List out of Range'

### ISSUE THREAD

**Issue by NickLambert** [OmniLayer/omniwallet#1672]
![image](https://user-images.githubusercontent.com/6389676/45622435-e32e3480-ba7b-11e8-8927-6f0d98187e08.png)

Wallet has failed to send MAID with the same error 'List out of Range'. Have been able to reproduce twice on OSX 10.13 running Chrome Version 68.0.3440.106. Have also been able to reproduce on Windows.

**Comment by gillbates** [comment]
same here, I cannot send usdt now ~~~

**Comment by achamely** [comment]
@NickLambert  @gillbates  This was related to the outage we had that day. If you refresh/try again now you should be able to proceed without any difficulties.

**Comment by NickLambert** [comment]
Yes working now, thanks for following up @achamely !
