### ISSUE TITLE
reverse my funds

### ISSUE THREAD

**Issue by Bakhtsalimkhan** [OmniLayer/omniwallet#1673]
binance key.....1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA
blockchain key....1LhPCNrBNoSVdRfUii2JbYydE7AqxzeZbd
isend btc to my blochaian wallet. but mistakly i send usdt in blochain id. but now show ominwallet. how can i reverse my usdt to my binance wallet plz help me. i attach my full history. 650usdt

**Comment by achamely** [comment]
@Bakhtsalimkhan We do not have the ability to reverse any transaction. If you accidentally sent USDt funds to your blockchain.info/.com  wallet address then you will need to take a look at the support article on how to export your private key and recover the funds manually: https://github.com/OmniLayer/omniwallet/wiki/Exporting-Private-Key-from-Blockchain.info-and-Importing-to-Omniwallet.org
