### ISSUE TITLE
Whether the official wallet supports Segregated Witness

### ISSUE THREAD

**Issue by romever** [OmniLayer/omniwallet#1674]
Now I have an address like "33AbVYAKBNaR2spub8VU7JC6eUNJG7B9qu" from other bitcoin wallet.I got a private key from website "https://iancoleman.io/bip39/" with BIP39 Mnemonic.Then I could get this address with BIP49.And I can also got private key matched this address.But when I used this private key import "omniwallet.org",I got an address like "1PeFEK49wUeQ8Xg9hiX5DhDcqoNqu6fbBt". How can I get Segregated Witness address from "omniwallet.org"?

**Comment by achamely** [comment]
@romever At the moment the wallet does not support importing segwit addresses. Please take a look at our support wiki article on recovering funds from a segwit address as an interim option: https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-from-a-Segwit-Address
