### ISSUE TITLE
more transfer 

### ISSUE THREAD

**Issue by midani81** [OmniLayer/omniwallet#1675]
How can I make more than one transfer at the same time from the same wallet ?
While I wanted to program a site that supports a CHILD WALLET for each member of my site, it may be that I have checked out more than one member at the same time

**Comment by macrotea** [comment]
i have the same question

**Comment by achamely** [comment]
@midani81 @macrotea  sorry for the delayed response. 
Omniwallet uses your addresses confirmed transactions when it creates a transaction. 
Depending on how many different BTC transactions were sent to your wallet will determine how many transactions you can create at a time. 
An option to enable multiple txs at once would be to send a few different btc transactions to your address of around 0.001 each. After confirmed they would be usable individually to create a send tx and the btc change from each tx, once confirmed would also be usable going forward for new txs
