### ISSUE TITLE
How can I create child wallet from public key?

### ISSUE THREAD

**Issue by deounix** [OmniLayer/omniwallet#1677]
How I can create child wallet from public key ?

Let's say that I've this address: 1MhRpv6wzbn7KsfDvbD4aEUkkJvdZp4Zoa
And this public key: 047FD2EC226707E9CA81B7253A24A46D5903AE678773E4F90DE7BF98D5B93C1F4C7F7571C0BBB30603B27576A91A1400B9A93BE06C126FEB6A376A60A6B2F85C29

So I want to create children wallets on this address: 1MhRpv6wzbn7KsfDvbD4aEUkkJvdZp4Zoa
So every one send usdt to this children should recive to my address : 1MhRpv6wzbn7KsfDvbD4aEUkkJvdZp4Zoa

Like Bitcoin. How can I do that ?

**Comment by achamely** [comment]
@deounix sorry for the delayed response, unfortunately this is not possible. 
On the Omni Protocol transactions are sent to a specific address and the funds are owned controlled only by the address they are sent to. 
You can not send funds to one address and have them credited to another. if you want the USDt to be received by 1MhRpv6wzbn7KsfDvbD4aEUkkJvdZp4Zoa, it needs to be sent to 1MhRpv6wzbn7KsfDvbD4aEUkkJvdZp4Zoa
