### ISSUE TITLE
weird display proplem

### ISSUE THREAD

**Issue by kemoantemo** [OmniLayer/omniwallet#1702]
![omni wallet](https://user-images.githubusercontent.com/19779701/52613644-6f138380-2e97-11e9-8aab-3af456862891.PNG)
why the wallet is displayed like this also this problem exist in my phone chrome android 7.0

**Comment by achamely** [comment]
@kemoantemo what you are seeing are the translation placeholders. But those should not be displayed as the system should automatically display the correct titles/words based on the region that is being requests. 
Can you please confirm what language or region your device is set for?

**Comment by kemoantemo** [comment]
my device usually english but i'm from egypt and we talk arabic so maybe some settings may refer to arabic regions

**Comment by achamely** [comment]
@kemoantemo thank you, we were able to isolate/find the issue in the arabic translation file that was causing the problem and have corrected it. you should see things displayed normally now
