### ISSUE TITLE
omnicore change file permision after copy blockes from another HDD

### ISSUE THREAD

**Issue by MohseniBigBoy** [OmniLayer/omniwallet#1704]
I use Omnicore (both testnet and mainnet) and everything is OK.
I use another HDD to lunch Omnicore in another PC, so I copied the blocks from the previous HDD to the new HDD, when I lunched Omnicore in the new PC, I see the block files permission changed to **+777**. 
I tested this work with some HDD but accrued same event.
when I test on another coins such as Bitcoin, Litecoin, Dash, ... this event **NOT** accrued and block files permission not changed !
This event does not make an error, but I'm worried about the +777 permission that is given to the files.
When I change the files permission manually, the synchronization starts from the beginning.

How to use from previous blocks while their permissions do not change?

**Comment by achamely** [comment]
Please post Omnicore questions to the omnicore project https://github.com/OmniLayer/omnicore/issues
