### ISSUE TITLE
How to transfer funds from multi source address?

### ISSUE THREAD

**Issue by mrzhengrui** [OmniLayer/omniwallet#1707]
I have many addresses which all have less funds, but how can I transfer these funds to one address in one time to save fee? I don't want to make many transfers.  In other words, to gather parts into a whole. This situation always happen in withdrawal  in exchange.

**Comment by achamely** [comment]
@mrzhengrui unfortunately you currently can not, there is no send 'from many' type of transaction yes, it is still currently in development. 
For now you will have to send from each address, one at a time.
