### ISSUE TITLE
API '/v2/address/addr/' always returns error: "This endpoint accepts at most 20 addresses."

### ISSUE THREAD

**Issue by triamazikamno** [OmniLayer/omniwallet#1714]
API endpoint `/v2/address/addr/` used to work well until recently, now it always returns error  "This endpoint accepts at most 20 addresses."
Error occurs even for the example request from the doc https://api.omniwallet.org/#request-v2-address-addr 
```
# curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Content-Type: application/x-www-form-urlencoded" -d "addr=1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA&addr=1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw" "https://api.omniwallet.org/v2/address/addr/"
{
  "error": "This endpoint accepts at most 20 addresses."
}
```

**Comment by achamely** [comment]
@triamazikamno the issue is fixed and the endpoint is working as documented again
