### ISSUE TITLE
can't login--website down

### ISSUE THREAD

**Issue by lifengllk** [OmniLayer/omniwallet#1720]
can't login now

https://www.omniwallet.org/

shows page below:

{{success.message}}, {{ 'MODALS.CONFIRM.CHECK' | translate }} {{ 'MODALS.CONFIRM.HERE' | translate }}.×
{{error.message}} ×
{{ 'COMMON.LOADING' | translate}}...

**Comment by lifengllk** [comment]
![image](https://user-images.githubusercontent.com/358433/56958362-b5b27900-6b7c-11e9-89d2-c4eecd0b650c.png)

**Comment by achamely** [comment]
@lifengllk can you confirm what language/region/locale your browser is trying to request?
This appears to be an issue specific to one of the translation files.

**Comment by achamely** [comment]
was resolved with https://github.com/OmniLayer/omniwallet/pull/1721
