### ISSUE TITLE
listsinceblock 查不出transactions

### ISSUE THREAD

**Issue by wang858** [OmniLayer/omniwallet#1733]
我用rpc命令listsinceblock 查不出交易的信息
![1563535758(1)](https://user-images.githubusercontent.com/36789456/61532198-a47e5780-aa5b-11e9-8506-4b46f478905d.jpg)
![image](https://user-images.githubusercontent.com/36789456/61532303-fa52ff80-aa5b-11e9-94b4-34d2098c4a8d.png)

但是我的地址是有交易的记录

**Comment by achamely** [comment]
Please post issues for omnicore in the omnicore repo  https://github.com/OmniLayer/omnicore

**Comment by wang858** [comment]
ok
