### ISSUE TITLE
Not showing balance when import

### ISSUE THREAD

**Issue by greetzimperio** [OmniLayer/omniwallet#1734]
Hello I have one question on my bitcoin address I have  some bitcoins but when I import private key on some other Bitcoin wallets as a blockchain It shows the balance on the address but on omniwallet it displays balance 0 Does anyone know why this is so?

**Comment by achamely** [comment]
@greetzimperio a backend process responsible for btc balance updates had frozen on monday. 
The issue has since been corrected and the wallet should display btc address properly
