### ISSUE TITLE
i lose my btc wallet also i lose my tether with i freak out

### ISSUE THREAD

**Issue by jaygosselin** [OmniLayer/omniwallet#1739]
what i can do for have back my tether usd is like same if is never exist

**Comment by jaygosselin** [comment]
can you help me please i lose 1400 usd and i cant found omggg

**Comment by achamely** [comment]
@jaygosselin Can you provide some more information about what exactly has happened?
Generally If you have lost your wallet there isn't much that can be done unless you have a backup. 
You can also contact our helpdesk directly for issues with the wallet.
