### ISSUE TITLE
Accidently sent USDT to robofore btc address

### ISSUE THREAD

**Issue by matin-code** [OmniLayer/omniwallet#1761]
I have accidently sent 3471$ usdt to roboforex btc address. is there any way i can get it back? 
i have searched and realized its possible butdont know how.
and i sent a ticket to roboforex support, can they help me recover it?

**Comment by achamely** [comment]
@matin-code They should be able to recover/return the funds as long as they can create an omni protocol tx. 
If they need help on how to do that you can let them know they can reach out to us and we can assist in the recovery process. 
However any recovery would have to be done by them and without their involvement there is nothing that can be done by anyone else.
