### ISSUE TITLE
Withdrawal Amount Haven't Recieved

### ISSUE THREAD

**Issue by MMoiz300** [OmniLayer/omniwallet#1775]
I withdraw my USDT from my Binance wallet to BTC mistakenly via Omni. Now my 105$ amount is deducted along with 5$ transaction charges and the recipient only received 0.6$. please assist. 

I can send all details of transaction.

**Comment by kylelew18** [comment]
follow. same issue here

**Comment by achamely** [comment]
@MMoiz300 @kylelew18  if you can access the private key of the BTC address the funds were sent to you can manually recover them (see support.omniwallet.org for recovery instructions). 
If you do not have access to the receiving address private key then your only option is to ask the receiving platform if they are willing to recover the funds for you.
