### ISSUE TITLE
Withdrawal 

### ISSUE THREAD

**Issue by yossi0605** [OmniLayer/omniwallet#1776]
I have been made a withdrawal from my USDT wallet in binance by OMNI to another wallet in binance 
By mistake it was not USDT wallet it was BTC wallet and the coin never arrive to the wallet and it’s go out from my account this is txid for the transaction 74ad9bda10a34a8680abf46fddbfe9c6ca4e5cc68572edf25843e9ec6204677f
And I will share screenshots for the transaction 
![CCD5F446-D97E-4378-8F8B-537B8173E761](https://user-images.githubusercontent.com/67347251/102978828-2eb2d100-4516-11eb-87a4-05478998922d.png)

**Comment by achamely** [comment]
@yossi0605 unfortunately nothing we can do. You need to contact Binance support and hope they are able to recover the funds for you. 
All funds are owned / controlled only by the address they are currently on so only Binance could access/recover those funds.
