### ISSUE TITLE
OmniWallet doesn't recognize my credentials

### ISSUE THREAD

**Issue by bspaugh** [OmniLayer/omniwallet#1777]
When I try to login I get a Sorry, we could not validate your credentials. Please check them and try again
If you continue to have difficulties, check out our Knowledge Base/Support Center
message.  It recognizes my info if I try to create a new account, but won't let me login. I tried with 2FA, Then with but did not get a code on either Authenticator or Authy.  
I invested in cryptos in 2017 and set them aside when I reached my allocation limit.  I am not trying to organize them into ZenLedger, and just organize them again period so I know how to access them when I want to add or trade.  I was originally in FireFox but then tried Chrome.  Same messages.  I would guess it is because of inactivity, but don't see a way to update or confirm my identity.
Please and thank you.

**Comment by achamely** [comment]
Please contact the support email for further assistance.
