### ISSUE TITLE
Omni to Omni Transaction

### ISSUE THREAD

**Issue by just2712** [OmniLayer/omniwallet#1778]
3 Days ago and the amount is not deposited(Still unconfirmed). From Omni USDT to Omni USDT Adress.

hash:
cd20b37b66fa4405eb24e2a39ca803835894355df742690003014715fb0c22ca

What is the Problem now? i saw it takes like 1hour and not more like 3-x days

best regards
just2712

**Comment by achamely** [comment]
The reason that tx is still unconfirmed is because the sender used a very low fee (14.139 sat/B). The current recommend network average is 102 sat/B. This has nothing to do with Omni/Tether and everything to do with using the right blockchain fees.
