### ISSUE TITLE
Omniwallet invalid BTC address

### ISSUE THREAD

**Issue by Dan3598328** [OmniLayer/omniwallet#1780]
Hello, I'm trying to send MAID from my Omniwallet.  It is requiring slightly more BTC than I have in the account for the transaction fee.  Whenever I try sending BTC to Omniwallet, I get an error message that the wallet address is invalid.  Sometimes it says something about Segwit.  Is there a way around this?

**Comment by achamely** [comment]
What is the address you are trying to send to?

**Comment by marvgmail** [comment]
If the user isn’t in a hurry, is it more cost efficient to just send his
maidsafe tokens with a smaller miner fee, rather than spending more Bitcoin
so he can then spend even more Bitcoin?
