### ISSUE TITLE
My fund is missed from spendable wallet

### ISSUE THREAD

**Issue by ylyu1206** [OmniLayer/omniwallet#1783]
How do I get my fund back that is missing from my spendable wallet?

**Comment by achamely** [comment]
Please provide more information about what you are seeing/what is happening. Either in this thread or by contacting support https://www.omniwallet.org/about/contact

**Comment by ylyu1206** [comment]
Hi Adam,
I moved funds into my wallet twice. After second one, my total amount was around $300.00 at 8/26. After I moved fund, I checked the movement was successfully. At 12:30PM 8/26, I looked at my account, the fund is not there anymore. My wallet address is 1CSkgCZuhqp3Bek7g1FSkRpWCNuG377ZSm. Can you recovery my fund for me?
[cid:7a455c9e-945b-4196-9d0b-c6329ddff2c6]
Best!
Yilang Yu

________________________________
