### ISSUE TITLE
Wallet equivocada

### ISSUE THREAD

**Issue by Canelabaking77** [OmniLayer/omniwallet#1784]
Hola, necesito ayuda. Iba a recibir un paga en la configuración puse una dirección de wallet de bitcoins y la dirección que debía colocar era de USDT, ellos enviaros lo fondos a la la dirección de mi wallet de bitcoins. Yo reclamé y me enviaron un link con la dirección de mi wallet y aparece el saldo en USDT, cómo puedo hacer para retirar ese saldo de esa billetera?

**Comment by achamely** [comment]
Sus opciones dependerán de si puede acceder a la clave privada de la dirección que recibió los fondos de USDt. Si puede exportar / acceder a la clave privada de la dirección de recepción, puede crear una nueva cuenta de Omniwallet e importar esa clave privada para recuperar el acceso a los fondos USDt que recibió. Si no tiene acceso a la clave privada, deberá comunicarse con el proveedor de la billetera y solicitar su ayuda para recuperar los fondos que recibió la dirección.
