### ISSUE TITLE
How to recover Sent tokens USDT to exchange "Coinbase" on the wrong network BTC Omni lost missing can't retrieve recieve or find my transactions 

### ISSUE THREAD

**Issue by Bhartman102890** [OmniLayer/omniwallet#1788]
How to recover Sent tokens USDT to exchange "Coinbase" on the wrong network BTC Omni lost missing can't retrieve recieve or find my transactions 

how to recover USDT sent to wrong network to an exchange! 
sent USDT over the BTC Omni network to Coinbase exchange. Used a Coinbase recieve address USDT token. Sent USDT from Gate.io exchange using BTC OMNI network. Coinbase recieved $.022 cents out of the $4558  I sent from Gate.io

**Comment by achamely** [comment]
Nothing we can do. Only Coinbase can access any funds sent to their deposit addresses. If they can't/won't recover then funds would remain stuck until they can
