### ISSUE TITLE
Sending crypto problem

### ISSUE THREAD

**Issue by qllio** [OmniLayer/omniwallet#1824]
I was using Omniwallet couple years ago, now I would like to send and trade my money, I have one wallet ID and inside two identical number address for Bitcoin and for Agoras. when im trying send Agoras I have info: you dont have BTC for  sending fee- what should I do? I should buy somewhere BTC and sent to wallet? Can I use my wallet address for BTC? how it works?  I should use network : ERC20 or OMNI to deposit?
Thank you for help

**Comment by AT78** [comment]
I use an Ellipal wallet and wanted to exchange from one coin to USDT.  For some reason, USDT(OMNI) was chosen and now i have USDT under BTC. Ellipal doesnt allow exchange back to other coins.  In an attempt to retrieve funds and use DEXm Sent USDT (Omni) to BTC wallet on omnilayer and but nowhere accepts USDT Omni.  How can I go from USDT omni back to another coin.  We're talking $$$'s dollars dormant and stuck.    Logged ticket with support yet no response.  If Omnilayer is no supported, shouldnt be accepting creating smart contracts with no way of retrieving funds.  Please help

**Comment by frankdavido** [comment]
Same issue here. 

I swapped my Monero to USDT only to realize it was really gone into USDT (OMNI).

I did the swapping on Guarda App

Now I can't seem to find a way to get back my money.

Anyone found a solution, please return here to tell us how you did.

Thanks
