### ISSUE TITLE
Footer design and behaviour

### ISSUE THREAD

**Issue by oktype** [OmniLayer/omniwallet#769]
![footer_min](https://cloud.githubusercontent.com/assets/6824303/3617258/a6127886-0ddc-11e4-98fa-4b8ceb6da533.jpg)

![footer_max](https://cloud.githubusercontent.com/assets/6824303/3617259/a6185b3e-0ddc-11e4-8fda-59eaa45a5d1c.jpg)

**Comment by achamely** [comment]
handled by rebrand update
