### ISSUE TITLE
Need a single style for confirmation modals and success/failure messages

### ISSUE THREAD

**Issue by marv-engine** [OmniLayer/omniwallet#772]
@oktype please work with Dave P (@enmaku) to define a single UI/UX style for all our confirmation modals and associated feedback messages.

Let's do something that's compatible with the current overall omni UI/UX so we can deploy it asap. Perfection is not required. If it's a bridge to the future, even better - but not necessary.

**Comment by achamely** [comment]
completed with new design on staging
